### PR TITLE
Urdf

### PR DESCRIPTION
**Pull request by alters-mit**
#### `RobotCreator`

- Added: `robot_creator.py` **Frontend users can now add robots to TDW, given the URL of a .urdf or .xacro file.** See: `tdw/Documenation/misc_frontend/robotics.md` and `tdw/Documentation/python/robot_creator.md`

#### Backend

- Added: `asset_bundle_creator_base.py` Shared code between `asset_bundle_creator.py` and `robot_creator.py`

### Robot Library

- Added new robots: Baxter, Sawyer, Niryo One, Fetch, Shadowhand, UR5, and UR10

### Example Controllers

- `robot_arm.py` uses the UR5 robot instead of the UR3 robot.

#### New Documentation

| Document | Description |
| --- | --- |
| `robot_creator.md`             | API documentation for `RobotCreator` as well as installation instructions and troubleshooting tips. |
| `asset_bundle_creator_base.md` | API documentation for `AssetBundleCreatorBase`               |

#### Modified Documentation

| Document                       | Modification                                                 |
| ------------------------------ | ------------------------------------------------------------ |
| `robots.md`                    | Added a section for how to start using the new `RobotCreator` |

### CODE REVIEW

**Review by jemsMIT — COMMENTED** [review]
> TDW include many real-world robots by default. 
Small typo

**Review by jemsMIT — COMMENTED** [review]
in robot_creator.md:

> Unity Editor 2020.2 (must be installed via Unity Editor)
Should this be Unity Hub?

There is no ROS install instructions for OSX.

Apart from that, this doc is great and very detailed!

**Review by jemsMIT — COMMENTED** [review]
You say this in the preable to the PR:

> Added new robots: Baxter, Sawyer, Niryo One, Fetch, Shadowhand, UR5, and UR10

Is this list mentioned anywhere in the doc?  We do say this:

> TDW include many real-world robots by default. Metadata records of each robot are stored in a RobotLibrarian.
> 
> To get a list of available robots:

Followed by the code snippet to print them out. That's great, but maybe indicate what this code will print out (as of the release of this feature)?

However if you feel that this should be left as "an exercise for the reader", I am open to being convinced.

**Comment by alters-mit** [comment]
>  Small typo

Fixed.

> Should this be Unity Hub?

Fixed.

> There is no ROS install instructions for OSX.

I don't know how to install ROS on OSX. It doesn't seem to be well supported. I found this, but it's not for the correct version of ROS, and I don't know if it installs everything we need: https://github.com/mikepurvis/ros-install-osx

There's two other links to OS X install pages on this site, but they seem to be empty: http://wiki.ros.org/Installation

Maybe it would be enough for now just to note in the documentation that support for converting .xacro files in OSX is not supported?

> However if you feel that this should be left as "an exercise for the reader", I am open to being convinced.

Yeah I think it should be, mostly because it won't be possible to keep the documentation up to date as we add more robots. For the same reason, we don't have a static list of models anywhere in our documentation.

**Pull request merged**
